training:
  nb_epochs: 10
  batch_size_train: 10
  batch_size_valid: 10

models:
  SimpleNet:
    type: SimpleNet
    optimizer:
      type: SGD
      params:
        lr: 0.01
        momentum: 0.5
        weight_decay: 0
    scheduler:
      type: ReduceLROnPlateau
      params:
        mode: 'min'
        factor: 0.1
        patience: 3
    criterion:
      type: CrossEntropyLoss
    metrics:
      - type: Accuracy

visdom:
  server: localhost
  port: 8097
  env: "Kerosene-MNIST"