training:
  nb_epochs: 10
  batch_size_train: 10
  batch_size_valid: 10

models:
  MNIST:
    type: SimpleNet
    params:
    optimizer:
      type: SGD
      params:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.1
    scheduler:
      type: ReduceLROnPlateau
      params:
        mode: 'min'
        factor: 0.1
        patience: 3
    criterion:
      type: CrossEntropyLoss
      params:
    metric:
      type: Accuracy
      params:

visdom:
  server: http://pldelisle.no-ip.info
  port: 8097
  env: "Kerosene-MNIST"